version: "3.9"
x-env: &env
  environment:
    MERCURE_RUNNER: docker

x-volumes: &volumes
  volumes:
    - config:/home/mercure/mercure/configuration
    - data:/home/mercure/data

x-volumes-docker: &volumes-docker
  volumes:
    - config:/home/mercure/mercure/configuration
    - data:/home/mercure/data
    - /var/run/docker.sock:/var/run/docker.sock

services:
  ui:
    depends_on:
      db:
        condition: service_healthy
    image: yarranyu/mercure-ui
    restart: always
    ports:
      - "8000:8000"
    <<: *volumes-docker
    <<: *env
  db:
    image: library/postgres:alpine
    restart: always
    env_file:
      - /opt/mercure/config/db.env
    environment:
      POSTGRES_USER: mercure
      POSTGRES_DB: mercure
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mercure" ]

  receiver:
    image: yarranyu/mercure-receiver
    restart: always
    depends_on:
      bookkeeper:
        condition: service_healthy
    ports:
      - "104:104"
    <<: *volumes
    <<: *env

  cleaner:
    image: yarranyu/mercure-cleaner
    restart: always
    depends_on:
      bookkeeper:
        condition: service_healthy
    <<: *volumes
    <<: *env

  dispatcher:
    image: yarranyu/mercure-dispatcher
    restart: always
    depends_on:
      bookkeeper:
        condition: service_healthy
    <<: *volumes
    <<: *env

  processor:
    image: yarranyu/mercure-processor
    restart: always
    depends_on:
      bookkeeper:
        condition: service_healthy
    <<: *volumes-docker
    <<: *env

  router:
    image: yarranyu/mercure-router
    restart: always
    depends_on:
      bookkeeper:
        condition: service_healthy
    <<: *volumes
    <<: *env

  bookkeeper:
    image: yarranyu/mercure-bookkeeper
    restart: always
    depends_on:
      db:
        condition: service_healthy
    <<: *volumes
    <<: *env

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/mercure/db'

  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/mercure/data'

  config:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/mercure/config'